//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/GamepadControllers.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GamepadControllers: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GamepadControllers()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GamepadControllers"",
    ""maps"": [
        {
            ""name"": ""Controller"",
            ""id"": ""2e3122a8-4e45-46ba-8913-df654e4d557b"",
            ""actions"": [
                {
                    ""name"": ""MenuNext"",
                    ""type"": ""Button"",
                    ""id"": ""1f26ce9b-4ac6-4c5b-9361-773154dcab76"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""moveAction"",
                    ""type"": ""Value"",
                    ""id"": ""75a097eb-b98f-40aa-8ad1-5215bba3da3d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""lookAction"",
                    ""type"": ""Value"",
                    ""id"": ""8668d458-ebfb-497e-b097-9487b4ecbcf6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""throttleUpAction"",
                    ""type"": ""Value"",
                    ""id"": ""d1e30f97-3f56-4591-870d-bd87084f60c9"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""throttleDownAction"",
                    ""type"": ""Value"",
                    ""id"": ""1a4875ba-c6e1-4a04-b1ac-9f2d8b249983"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PopupConfirm"",
                    ""type"": ""Button"",
                    ""id"": ""1574745c-55ca-4068-8564-551840dffa89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Test"",
                    ""type"": ""Button"",
                    ""id"": ""68e5fcd0-eefc-4b7e-8e77-388d51a5c616"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5f7ca645-b26c-4fe3-aa69-4f09f8254142"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fb729f7-99ab-43b9-9141-27e30a9dbad5"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Test"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1151e730-2c49-4527-a1f0-f84daaa88b5b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveAction"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d64ff41e-908d-457c-aa65-11809e198613"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f8d9931b-c6d4-4d03-badf-1c30789cf4c9"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0af16306-beb1-47ef-bdb6-c76f5d5df1d4"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cc881612-f63d-4586-8f46-395b825b1848"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""de7f9dc8-1edc-4d3f-88b1-7b061021b0d1"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""03a6b2eb-2087-4b83-9e31-9f3e9df1c402"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""44f54983-025e-4f20-b485-f984b8187f52"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d45e87ed-ed4f-49b1-8f0a-389d70506d4d"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e2e7e542-b9b3-4198-9a37-b169f2e2ce56"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""lookAction"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""af1a9eba-4ed7-4437-a834-2f4c707767d3"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""lookAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2dba08b2-867a-418b-9d07-967e5c236770"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""lookAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c2d7f525-445b-418e-a18c-1426910f7e7b"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""lookAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""db172457-df1a-4cc1-8fbe-65bf8a7be22f"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""lookAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""52c3f127-5bf2-45f5-a4c8-77905abc3cc3"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throttleUpAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e281c8db-bf9a-4771-bb9c-3a9344f06be1"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throttleUpAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38e07e26-03e4-4742-b8e8-8522060d92d2"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throttleUpAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbb71975-a729-4c16-802a-4a9f7a956f52"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throttleDownAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31f08051-b46c-42e1-9266-d437b595fd4a"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throttleDownAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d69d14ae-c4b9-45b6-be8f-fcfd2e8c1fd7"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throttleDownAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2095724c-b144-41d1-b823-85f38402c4e6"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PopupConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a85df18e-44bc-45c7-a927-f934ed76094b"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PopupConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Controller
        m_Controller = asset.FindActionMap("Controller", throwIfNotFound: true);
        m_Controller_MenuNext = m_Controller.FindAction("MenuNext", throwIfNotFound: true);
        m_Controller_moveAction = m_Controller.FindAction("moveAction", throwIfNotFound: true);
        m_Controller_lookAction = m_Controller.FindAction("lookAction", throwIfNotFound: true);
        m_Controller_throttleUpAction = m_Controller.FindAction("throttleUpAction", throwIfNotFound: true);
        m_Controller_throttleDownAction = m_Controller.FindAction("throttleDownAction", throwIfNotFound: true);
        m_Controller_PopupConfirm = m_Controller.FindAction("PopupConfirm", throwIfNotFound: true);
        m_Controller_Test = m_Controller.FindAction("Test", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Controller
    private readonly InputActionMap m_Controller;
    private List<IControllerActions> m_ControllerActionsCallbackInterfaces = new List<IControllerActions>();
    private readonly InputAction m_Controller_MenuNext;
    private readonly InputAction m_Controller_moveAction;
    private readonly InputAction m_Controller_lookAction;
    private readonly InputAction m_Controller_throttleUpAction;
    private readonly InputAction m_Controller_throttleDownAction;
    private readonly InputAction m_Controller_PopupConfirm;
    private readonly InputAction m_Controller_Test;
    public struct ControllerActions
    {
        private @GamepadControllers m_Wrapper;
        public ControllerActions(@GamepadControllers wrapper) { m_Wrapper = wrapper; }
        public InputAction @MenuNext => m_Wrapper.m_Controller_MenuNext;
        public InputAction @moveAction => m_Wrapper.m_Controller_moveAction;
        public InputAction @lookAction => m_Wrapper.m_Controller_lookAction;
        public InputAction @throttleUpAction => m_Wrapper.m_Controller_throttleUpAction;
        public InputAction @throttleDownAction => m_Wrapper.m_Controller_throttleDownAction;
        public InputAction @PopupConfirm => m_Wrapper.m_Controller_PopupConfirm;
        public InputAction @Test => m_Wrapper.m_Controller_Test;
        public InputActionMap Get() { return m_Wrapper.m_Controller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControllerActions set) { return set.Get(); }
        public void AddCallbacks(IControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_ControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControllerActionsCallbackInterfaces.Add(instance);
            @MenuNext.started += instance.OnMenuNext;
            @MenuNext.performed += instance.OnMenuNext;
            @MenuNext.canceled += instance.OnMenuNext;
            @moveAction.started += instance.OnMoveAction;
            @moveAction.performed += instance.OnMoveAction;
            @moveAction.canceled += instance.OnMoveAction;
            @lookAction.started += instance.OnLookAction;
            @lookAction.performed += instance.OnLookAction;
            @lookAction.canceled += instance.OnLookAction;
            @throttleUpAction.started += instance.OnThrottleUpAction;
            @throttleUpAction.performed += instance.OnThrottleUpAction;
            @throttleUpAction.canceled += instance.OnThrottleUpAction;
            @throttleDownAction.started += instance.OnThrottleDownAction;
            @throttleDownAction.performed += instance.OnThrottleDownAction;
            @throttleDownAction.canceled += instance.OnThrottleDownAction;
            @PopupConfirm.started += instance.OnPopupConfirm;
            @PopupConfirm.performed += instance.OnPopupConfirm;
            @PopupConfirm.canceled += instance.OnPopupConfirm;
            @Test.started += instance.OnTest;
            @Test.performed += instance.OnTest;
            @Test.canceled += instance.OnTest;
        }

        private void UnregisterCallbacks(IControllerActions instance)
        {
            @MenuNext.started -= instance.OnMenuNext;
            @MenuNext.performed -= instance.OnMenuNext;
            @MenuNext.canceled -= instance.OnMenuNext;
            @moveAction.started -= instance.OnMoveAction;
            @moveAction.performed -= instance.OnMoveAction;
            @moveAction.canceled -= instance.OnMoveAction;
            @lookAction.started -= instance.OnLookAction;
            @lookAction.performed -= instance.OnLookAction;
            @lookAction.canceled -= instance.OnLookAction;
            @throttleUpAction.started -= instance.OnThrottleUpAction;
            @throttleUpAction.performed -= instance.OnThrottleUpAction;
            @throttleUpAction.canceled -= instance.OnThrottleUpAction;
            @throttleDownAction.started -= instance.OnThrottleDownAction;
            @throttleDownAction.performed -= instance.OnThrottleDownAction;
            @throttleDownAction.canceled -= instance.OnThrottleDownAction;
            @PopupConfirm.started -= instance.OnPopupConfirm;
            @PopupConfirm.performed -= instance.OnPopupConfirm;
            @PopupConfirm.canceled -= instance.OnPopupConfirm;
            @Test.started -= instance.OnTest;
            @Test.performed -= instance.OnTest;
            @Test.canceled -= instance.OnTest;
        }

        public void RemoveCallbacks(IControllerActions instance)
        {
            if (m_Wrapper.m_ControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_ControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControllerActions @Controller => new ControllerActions(this);
    public interface IControllerActions
    {
        void OnMenuNext(InputAction.CallbackContext context);
        void OnMoveAction(InputAction.CallbackContext context);
        void OnLookAction(InputAction.CallbackContext context);
        void OnThrottleUpAction(InputAction.CallbackContext context);
        void OnThrottleDownAction(InputAction.CallbackContext context);
        void OnPopupConfirm(InputAction.CallbackContext context);
        void OnTest(InputAction.CallbackContext context);
    }
}
